### ISSUE TITLE
Hard-coded language strings in multiple places

### ISSUE THREAD

**Issue by volodymyrdovhan** [BM373/moodle-mod_videoassessment#24]
Hello,

I noticed hard-coded language strings in some files. All user-facing strings should be defined in the language file and displayed using the get_string() function.
https://moodledev.io/general/community/plugincontribution/checklist#strings 

![Image](https://github.com/user-attachments/assets/db616cc0-a305-4f02-99d7-42061650d97a)

![Image](https://github.com/user-attachments/assets/8fb6243b-f098-4eab-b867-3071872908b6)

![Image](https://github.com/user-attachments/assets/69734ac7-c680-4905-bd94-842c521405f4)

![Image](https://github.com/user-attachments/assets/c9f3dce0-a797-4e9a-8496-32924e7ff741)

![Image](https://github.com/user-attachments/assets/e395d3db-29f0-491c-aeac-d4073113d7da)

![Image](https://github.com/user-attachments/assets/c37a84a6-f9bc-4437-9cf5-31c69b0a13cb)

![Image](https://github.com/user-attachments/assets/876bab47-5199-4f82-ad0b-821c5c1533ed)

![Image](https://github.com/user-attachments/assets/7aef1d47-4b3f-4eb5-9a63-b0f797f69f1a)

![Image](https://github.com/user-attachments/assets/fe9cc1fc-d73d-48ab-ab88-e70a8dba0451)

![Image](https://github.com/user-attachments/assets/d4a3517f-bf12-46a8-9ed0-6408b001dc4d)

![Image](https://github.com/user-attachments/assets/9b7b5e43-0d49-482d-b9f7-0673c260268d)

![Image](https://github.com/user-attachments/assets/c062f3d7-fd4d-4815-a4c1-8f5482cb7d2f)

![Image](https://github.com/user-attachments/assets/da5d1396-84f6-4407-89d1-5bfa36b7498f)

**Comment by BM373** [comment]
Issue addressed in Version 2025092400.

**Comment by volodymyrdovhan** [comment]
Hello,
The issues remain:

<img width="951" height="658" alt="Image" src="https://github.com/user-attachments/assets/af8cc81e-a45d-43c2-8039-6f027da7e2b6" />

<img width="1082" height="762" alt="Image" src="https://github.com/user-attachments/assets/0ae33f5d-b928-47ac-8913-f24dc2b162ba" />

<img width="1025" height="496" alt="Image" src="https://github.com/user-attachments/assets/dc7649b2-eb16-4c16-aff7-9e136d3c530d" />

<img width="1097" height="606" alt="Image" src="https://github.com/user-attachments/assets/d6ba9806-7f44-42fd-b83b-1d53f877ca77" />

<img width="1237" height="798" alt="Image" src="https://github.com/user-attachments/assets/d6e5cc56-d2fb-43a5-9e9a-bb2fc931240f" />

<img width="813" height="803" alt="Image" src="https://github.com/user-attachments/assets/053327db-69f9-4d03-9450-144bdab68e97" />

<img width="1003" height="784" alt="Image" src="https://github.com/user-attachments/assets/b32fc4e3-73c9-4223-87b3-b9ed120e2d62" />

<img width="1045" height="772" alt="Image" src="https://github.com/user-attachments/assets/c04cd144-0f65-465e-a76c-8503ee5f2b0d" />

**Comment by BM373** [comment]
Issue addressed in 20251006 update.
