### ISSUE TITLE
$DB->execute() usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [BM373/moodle-mod_videoassessment#26]
Hello,

I noticed that the plugin uses $DB->execute($sql, $params); for database operations. According to Moodle documentation, the execute method should only be used when no specialised method exists.

It's recommended to use standard Moodle DML functions like update_record(), insert_record(),, insert_records(), get_records(), or delete_records() for better compatibility, security, and performance.

Please refer to the documentation for more details:[ Moodle DML API - execute()](https://moodledev.io/docs/4.5/apis/core/dml#execute)

![Image](https://github.com/user-attachments/assets/5762dc7a-36d8-4862-9088-965e0d95c359)

![Image](https://github.com/user-attachments/assets/42e70d76-bf20-437b-83db-b4dbab430010)

![Image](https://github.com/user-attachments/assets/bda328ba-9f6a-457e-914b-aad8ba1ae580)

**Comment by BM373** [comment]
Issue addressed in Version 2025092400.

**Comment by volodymyrdovhan** [comment]
Hello,
The issue remains:

<img width="1001" height="727" alt="Image" src="https://github.com/user-attachments/assets/ada19a4f-b9e5-477a-9435-a25913b26b28" />

<img width="852" height="605" alt="Image" src="https://github.com/user-attachments/assets/c34272b2-a6d8-4fa8-b7bc-d82a98136a3e" />

**Comment by BM373** [comment]
Issue addressed in 20251006 update.
