### ISSUE TITLE
Non-existing methods/functions usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [BM373/moodle-mod_videoassessment#27]
Hello,

I found a few methods/function usage which don't exist in the plugin.
Please revisit the code.

![Image](https://github.com/user-attachments/assets/4b54bb7d-785f-4285-ba30-26588d060d42)

![Image](https://github.com/user-attachments/assets/9e34dc6b-98ca-4a86-b4ab-173f0052c111)

![Image](https://github.com/user-attachments/assets/010d05af-1b5b-44a5-bac0-5d5807a32b20)

![Image](https://github.com/user-attachments/assets/86fa12a8-d0f2-4225-a006-0b5f693254b8)

**Comment by BM373** [comment]
Issue addressed in Version 2025092400.

**Comment by volodymyrdovhan** [comment]
Hello,
The issues remain:

<img width="1074" height="500" alt="Image" src="https://github.com/user-attachments/assets/b9af4367-2e3b-4406-836b-e728dcc5965a" />

<img width="1373" height="622" alt="Image" src="https://github.com/user-attachments/assets/31703ae0-6cac-417c-beea-d548daaaa438" />

<img width="1028" height="630" alt="Image" src="https://github.com/user-attachments/assets/644499a7-0745-469f-b7ba-39e098cf9dfe" />

<img width="1007" height="613" alt="Image" src="https://github.com/user-attachments/assets/fbdcd9e0-a517-44bd-b6db-74cf94ac374d" />

<img width="1041" height="438" alt="Image" src="https://github.com/user-attachments/assets/ebeb810c-2fe6-44fd-8c17-7ecce42f906a" />

**Comment by BM373** [comment]
Issue addressed in 20251006 update.
