### ISSUE TITLE
Missing language strings in the language file

### ISSUE THREAD

**Issue by volodymyrdovhan** [BM373/moodle-mod_videoassessment#28]
Hello,

I found language strings usage which not defined in the language file. Please revisit the code.

![Image](https://github.com/user-attachments/assets/925b03fd-84f8-46ee-adb8-4106b13930c3)

![Image](https://github.com/user-attachments/assets/2f018593-8a7d-4444-b7ff-da13fd465e91)

![Image](https://github.com/user-attachments/assets/83397c2a-71f0-4a74-a7ff-48df6aba73f8)

![Image](https://github.com/user-attachments/assets/ed8cca4b-273f-42b0-b675-3573cf5e59b2)

![Image](https://github.com/user-attachments/assets/728009b2-ae97-463f-b35d-9d9b7c2f0e9e)

![Image](https://github.com/user-attachments/assets/9a569005-1f72-45de-8d0e-5343f109910e)

![Image](https://github.com/user-attachments/assets/42d517f3-287d-486b-b124-5064a57aa874)

![Image](https://github.com/user-attachments/assets/558a11d9-736a-4747-883b-ee0dc5daddb3)

**Comment by BM373** [comment]
Issue addressed in Version 2025092400.

**Comment by volodymyrdovhan** [comment]
Hello,
The issues remain:

<img width="1088" height="598" alt="Image" src="https://github.com/user-attachments/assets/a71fb817-7286-4508-a505-881b8ceb173c" />

<img width="1045" height="507" alt="Image" src="https://github.com/user-attachments/assets/aa65327a-47b8-468e-872a-27bbd9b1a4b0" />

<img width="831" height="722" alt="Image" src="https://github.com/user-attachments/assets/34b0bcce-430f-4883-a0f8-13d587682d3b" />

<img width="1154" height="707" alt="Image" src="https://github.com/user-attachments/assets/b7a61e54-d0ff-4dd6-915a-0381916b35fb" />

<img width="1304" height="419" alt="Image" src="https://github.com/user-attachments/assets/b57df135-8b66-4900-b234-35d9fb54fe3a" />

<img width="908" height="771" alt="Image" src="https://github.com/user-attachments/assets/ec9c2f0d-4e5a-4cc9-9c44-728e4a04aba9" />

**Comment by BM373** [comment]
Issue addressed in 20251006 update.
