### ISSUE TITLE
Missing capabilities validation

### ISSUE THREAD

**Issue by volodymyrdovhan** [BM373/moodle-mod_videoassessment#37]
Hello,

Please review the plugin use cases and validate that the plugin checks capabilities correctly.
I found that some actions can be processed without any validation or just with course enrollment validation.

![Image](https://github.com/user-attachments/assets/011b207c-70a0-43dc-854b-837e8783c289)

![Image](https://github.com/user-attachments/assets/6a5ff971-64a1-4507-b649-b59ee574578a)

![Image](https://github.com/user-attachments/assets/0957b820-3d7e-452a-a583-91f353f225a8)

![Image](https://github.com/user-attachments/assets/7a9bc182-3a3c-485f-9bed-3f79601e0557)

![Image](https://github.com/user-attachments/assets/aaf09e9c-da8f-414a-9a20-ed5ab3618cb5)

**Comment by BM373** [comment]
Issue addressed in Version 2025092400.

**Comment by volodymyrdovhan** [comment]
Hello,
In some files, the capability validation is still missing or validates after some actions:

<img width="969" height="687" alt="Image" src="https://github.com/user-attachments/assets/5d8b85ca-5199-468c-819d-d0f1cb3b3cc6" />

<img width="1083" height="744" alt="Image" src="https://github.com/user-attachments/assets/db34d458-348b-4c8d-b312-0d13355f3dac" />

**Comment by BM373** [comment]
Issue addressed in 20251006 update.
